[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ong-data-pipeline"
version = "0.1.0"
description = "ONG pipeline"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "dotenv>=0.9.9",
    "gspread>=6.2.1",
    "pandas>=3.0.3",
    "pandas-gbq>=0.35.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["ong_data_pipeline*"]
